# Generated by Django 5.1.6 on 2025-02-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('role', models.CharField(choices=[('Event_Manager', 'Event Manager'), ('User', 'User')], max_length=50)),
            ],
        ),
    ]
