# Generated by Django 5.1.5 on 2025-02-06 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('phone_number', models.PositiveIntegerField(blank=True, null=True)),
                ('role', models.CharField(choices=[('Event_Manager', 'Event_Manager'), ('User', 'User')], default='User', max_length=50)),
            ],
        ),
    ]
