# Generated by Django 5.1.5 on 2025-04-04 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_user_options_alter_user_managers_and_more'),
        ('polls', '0004_searchedarea_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
    ]
