# Generated by Django 5.1.6 on 2025-04-24 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_searchedarea_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Event_Manager', 'Event Manager'), ('User', 'User')], default='User', max_length=20),
        ),
    ]
