# Generated by Django 5.1.3 on 2025-04-21 04:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):



    operations = [
        migrations.RemoveField(
            model_name='event',
            name='place_id',
        ),
        migrations.CreateModel(
            name='POI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('place_id', models.CharField(blank=True, help_text='Unique ID from the data source (e.g., Geoapify place_id)', max_length=255, null=True, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location_name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('event_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pois', to='polls.user')),
            ],
        ),
    ]
