# Generated by Django 5.1.5 on 2025-04-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location_name',
            field=models.CharField(max_length=255),
        ),
    ]
