# Generated by Django 5.1.5 on 2025-04-22 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_merge_20250403_2256'),
        ('polls', '0006_remove_event_place_id_poi'),
        ('polls', '0006_remove_user_groups_remove_user_is_active_and_more'),
    ]

    operations = [
    ]
