# Generated by Django 5.1.5 on 2025-04-22 04:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_merge_20250421_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(blank=True, choices=[('Festival', 'Festival'), ('Convention', 'Convention'), ('Business', 'Business'), ('Concert', 'Concert'), ('Exhibition', 'Exhibition'), ('Recreational', 'Recreational'), ('Social', 'Social'), ('Misc', 'Misc')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events', models.ManyToManyField(blank=True, related_name='parkings', to='polls.event')),
                ('poi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parkings', to='polls.poi')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('events', models.ManyToManyField(blank=True, related_name='plans', to='polls.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='polls.user')),
            ],
        ),
    ]
