# Generated by Django 5.1.3 on 2025-04-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_rename_event_date_event_end_date_event_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='pois',
            field=models.ManyToManyField(blank=True, related_name='plans', to='polls.poi'),
        ),
    ]
